a=input("Enter Your Name")
b=int(input("Enter Your Age"))
c=input("Enter Your School")
d=int(input("Enter Your Grade"))
e=input("Enter Your Favourite Subject")
print("Name:", a)
print("Age:", b)
print("School:", c)
print("Grade:", d)
print("Favourite Subject:", e)